In [2]:
#Importação das bibliotecas
import pandas as pd
import sklearn as sk

#Conjunto de dados criado
dados_clientes = {
    'idade_cliente': [22, 25, 28, 30, 34, 37, 40, 45, 29, 33],
    'tempo_cadastro_meses': [2, 6, 12, 18, 24, 30, 36, 48, 10, 20],
    'email_aberto': [True, True, False, True, True, False, True, False, True, False],
    'clicou_no_link': [False, True, False, True, False, False, True, True, True, False],
    'realizou_compra': [False, True, False, True, True, False, True, True, True, False]
}

#Criando DataFrame
df_clientes = pd.DataFrame(dados_clientes)

#Exibindo teste do conjunto de dados
df_clientes.head()

,idade_cliente,tempo_cadastro_meses,email_aberto,clicou_no_link,realizou_compra
0,22,2,True,False,False
1,25,6,True,True,True
2,28,12,False,False,False
3,30,18,True,True,True
4,34,24,True,False,True

In [4]:
#Dividindo conjunto de dados em variáveis independentes e dependentes
x = df_clientes.drop('realizou_compra', axis=1)
y = df_clientes['realizou_compra']

print("Variáveis Independentes (X):")
display(x.head())

print("\nVariável Dependente (y):")
display(y.head())

Variáveis Independentes (X):

   idade_cliente  tempo_cadastro_meses  email_aberto  clicou_no_link
0             22                     2          True           False
1             25                     6          True            True
2             28                    12         False           False
3             30                    18          True            True
4             34                    24          True           False

Variável Dependente (y):

0    False
1     True
2    False
3     True
4     True
Name: realizou_compra, dtype: bool

In [7]:
#Criando variáveis de treino e de teste
x_treino, x_teste, y_treino, y_teste = sk.model_selection.train_test_split(x, y, test_size=0.2, random_state=42)

#Criando árvore de decisão
modelo_arvore = sk.tree.DecisionTreeClassifier()

#Treinando o modelo
modelo_arvore.fit(x_treino, y_treino)

#Fazendo Previsões
previsoes = modelo_arvore.predict(x_teste)

In [9]:
#Avaliação da acurácia
acuracia = sk.metrics.accuracy_score(y_teste, previsoes)
print(f"Acurácia do Modelo: {acuracia * 100:.2f}%")

Acurácia do Modelo: 100.00%

**Para este modelo encontramos a acurácia de 100%, o que significa que o modelo conseguiu prever todos os resultados do conjunto de dados.**